"
" lkx810
" 2018/04/06
" https://dougblack.io/words/a-good-vimrc.html
" https://vimawesome.com/
"

" Plug {{{
call plug#begin('~/.vim/plugged')

" Vim
Plug 'vimwiki/vimwiki'
let g:vimwiki_list = [{'path': '~/.wiki/'}]
Plug 'junegunn/vim-easy-align'
Plug 'ctrlpvim/ctrlp.vim'
let g:ctrlp_match_window = 'bottom,order:ttb'
let g:ctrlp_switch_buffer = 0
let g:ctrlp_working_path_mode = 0
let g:ctrlp_custom_ignore = '\vbuild/|dist/|venv/|target/|\.(o|swp|pyc|egg)$'

" Color & Highlight
Plug 'joshdick/onedark.vim'
Plug 'sheerun/vim-polyglot'

" UI
Plug 'vim-airline/vim-airline'
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#show_tabs = 1
let g:airline#extensions#tabline#show_buffers = 0
let g:airline_theme='onedark'
Plug 'airblade/vim-gitgutter'
Plug 'scrooloose/nerdtree'
Plug 'mhinz/vim-startify'

" Move
Plug 'easymotion/vim-easymotion'
Plug 'christoomey/vim-tmux-navigator'
Plug 'justinmk/vim-sneak'

" Edit
Plug 'tpope/vim-surround'
Plug 'scrooloose/nerdcommenter'
Plug 'junegunn/vim-easy-align'

" Lint
Plug 'w0rp/ale'
let g:ale_linters = {
      \   'python': ['flake8'],
      \   'C++': ['clang-format'],
      \}
let g:ale_fix_on_save = 1
let g:ale_lint_on_text_changed = 'never'

" Cpp
Plug 'vim-scripts/a.vim', { 'for': 'cpp' }

" Initialize plugin system
call plug#end()
" }}}

" Colorscheme {{{
set termguicolors
set background=dark   " require
syntax enable
colorscheme onedark
" }}}
" Misc {{{
set synmaxcol=200
set scrolloff=3                 " Minimum lines to keep above and below cursor
set backspace=indent,eol,start
set laststatus=2
set statusline=\ %{HasPaste()}%F%m%r%h\ %w\ \ CWD:\ %r%{getcwd()}%h\ \ \ Line:\ %l\ \ Column:\ %c
" disable Background Color Erase (BCE) so that color schemes
" render properly when inside 256-color tmux and GNU screen.
" see also http://snk.tuxfamily.org/log/vim-256color-bce.html
" https://sunaku.github.io/vim-256color-bce.html#solution
if &term =~ '256color'
    set t_ut=
endif
" remember last position
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif
" }}}
" Shell {{{
set shell=/bin/zsh
autocmd BufWinEnter,WinEnter term://* startinsert
set splitbelow
set splitright
" }}}
" Indent {{{
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set smarttab
filetype indent on
filetype plugin on
set autoindent
" }}}
" UI {{{
" Disable scrollbars
set guioptions-=r
set guioptions-=R
set guioptions-=l
set guioptions-=L

set ttyfast     " Speed up
set showcmd
set wildmenu
set number
set lazyredraw
set nocursorline " highlight current line
set fillchars+=vert:┃
" }}}
" Folding {{{
set foldenable          " enable folding
set foldmethod=indent   " fold based on indent level
set foldnestmax=10      " max 10 depth
set modelines=1         " tell Vim to check just the final line of the file for a modeline
nnoremap <space> za
set foldlevelstart=10   " start with fold level of 1
" }}}
" Search {{{
set smartcase
set incsearch   " search as characters are entered
set hlsearch    " highlight matches
" set showmatch   " highlight matching [{()}]
set ignorecase  " ignore case when searching
" }}}
" Leader Map Shortcuts {{{
let mapleader=";"
" Smart way to move between windows
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l
"
map <F2> :NERDTreeToggle<CR>
" Useful mappings for managing tabs
" Use `$vim -p` open multi files
map <leader>tn :tabnew<cr>
map <C-n>      :tabnew<cr>
map <leader>to :tabonly<cr>
map <leader>tc :tabclose<cr>
map <leader>tm :tabmove
map <leader>tt :tabnext<cr>
map <Tab> :tabnext<cr>
" Let 'tl' toggle between this and the last accessed tab
let g:lasttab = 1
nmap <Leader>tl :exe "tabn ".g:lasttab<CR>
au TabLeave * let g:lasttab = tabpagenr()
" }}}
" User Function {{{
command W w !sudo tee % > /dev/null
command Wq wq
set pastetoggle=<F3>
" }}}
" NERDTree {{{
autocmd StdinReadPre * let s:std_in=1
" open a NERDTree automatically when vim starts up if no files were specified
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
" open NERDTree automatically when vim starts up on opening a directory
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'NERDTree' argv()[0] | wincmd p | ene | endif
" close vim if the only window left open is a NERDTree
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
" }}}

" vim:foldmethod=marker:foldlevel=0
