export DOTFILES=$HOME/.dotfiles

# Judge which OS 
case "$(uname -s)" in
    Linux*)     machine=Linux;;
    Darwin*)    machine=Mac;;
    CYGWIN*)    machine=Cygwin;;
    MINGW*)     machine=MinGw;;
    *)          machine="UNKNOWN:${unameOut}"
esac

# Use tmux in terimal, but not in tty login in shell
case $- in *i*)
  if [ -z "$TMUX" ]; then [[ -o login ]] && [[ $machine -ne "Mac" ]] && echo 'Hello -!' || exec tmux -2 ; fi;;
esac

source $DOTFILES/zsh/antigen.zsh
# Load the oh-my-zsh's library.
antigen use oh-my-zsh

antigen bundles <<EOBUNDLES
# Bundles from the default repo (robbyrussell's oh-my-zsh).
  git                  # extras: git-extras gitfast git-flow git-flow-avh git-hubflow git-remote-branch
  gitignore            # gi alias to fetch default .gitignore files from http://gitignore.io/
  github               # cli access, url shortener

  extract              # 'x' alias - swiss knife for archive extracting
  cp                   # cp with progress bar (rsync)

  colored-man-pages    # adds colors to manpages

# unixorn/warhol.plugin.zsh               # Colorize command output using grc and lscolors

  zsh-users/zsh-autosuggestions
  zsh-users/zsh-completions
  zsh-users/zsh-syntax-highlighting
  zsh-users/zsh-history-substring-search

  rupa/z
EOBUNDLES

# Load the theme.
# If change theme, run ` $ antigen reset `
# antigen theme robbyrussell
# antigen theme fox
antigen theme $DOTFILES/zsh/theme oxide --no-local-clone

# Tell Antigen that you're done.
antigen apply

# configure autosuggestions
bindkey '^f' forward-word

# run $fzf
# pacman -S fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

source $DOTFILES/zsh/history.zsh
source $DOTFILES/zsh/export.zsh
source $DOTFILES/zsh/alias.zsh
source $DOTFILES/zsh/function.zsh
[ -f $DOTFILES/zsh/zsh.local ] && source $DOTFILES/zsh/zsh.local
