export DOTFILES=$HOME/.dotfiles

[ -f $DOTFILES/zsh/antigen.zsh  ] || curl -L git.io/antigen > $DOTFILES/zsh/antigen.zsh 

source $DOTFILES/zsh/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

antigen bundles <<EOBUNDLES
# Bundles from the default repo (robbyrussell's oh-my-zsh).
  git                  # extras: git-extras gitfast git-flow git-flow-avh git-hubflow git-remote-branch
  gitignore            # gi alias to fetch default .gitignore files from http://gitignore.io/
  github               # cli access, url shortener
  command-not-found    

  extract              # 'x' alias - swiss knife for archive extracting
  cp                   # cp with progress bar (rsync)
  fzf                  # fuzzy search command using Ctrl-R
  git-open             # open remote url
  web-search

  colored-man-pages    # adds colors to manpages

  zsh-users/zsh-autosuggestions
  zsh-users/zsh-completions
  zsh-users/zsh-syntax-highlighting
  zsh-users/zsh-history-substring-search

  rupa/z
EOBUNDLES

# Load the theme.
# If change theme, run ` $ antigen reset `
# antigen theme robbyrussell
# antigen theme fox
antigen theme $DOTFILES/zsh/theme oxide --no-local-clone

# Tell Antigen that you're done.
antigen apply

# configure autosuggestions
bindkey '^f' forward-word

source $DOTFILES/zsh/history.zsh
source $DOTFILES/zsh/user.setting.zsh
[ -f $DOTFILES/zsh/zsh.local ] && source $DOTFILES/zsh/zsh.local
